# Generated by Django 4.1.4 on 2023-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_photos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='img',
            new_name='img_large',
        ),
        migrations.AddField(
            model_name='photos',
            name='img_small',
            field=models.ImageField(default='Pictures', upload_to='Pics'),
        ),
    ]
