# Generated by Django 4.1.4 on 2023-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_img_photos_img_large_photos_img_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('img_large', models.ImageField(upload_to='Pics')),
                ('img_small', models.ImageField(default='Pictures', upload_to='Pics')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('img_large', models.ImageField(upload_to='Pics')),
                ('img_small', models.ImageField(default='Pictures', upload_to='Pics')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Drones',
        ),
        migrations.AlterModelOptions(
            name='drones',
            options={'ordering': ('name',), 'verbose_name': 'Drone', 'verbose_name_plural': 'Drones'},
        ),
    ]
